version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "SimpleDB"
      POSTGRES_USER: "SimpleDB"
      POSTGRES_PASSWORD: "SimpleDB"
    ports:
      - "5432:5432"