version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_USER: "SimpleDB"
      POSTGRES_PASSWORD: "SimpleDB"
    volumes:
      - ./simple-db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"